name: Docker Image CI

on:
  push:
    branches: [ master, main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build the Docker image
        uses: actions/checkout@v2
        run: |
          echo docker build . --file Dockerfile \
            --tag docker.io/$/$:$GITHUB_SHA
          docker push docker.io/$/$:$GITHUB_SHA
